workspace:
  base: /metaron
  path: src/github.com/razem-io/metatron

pipeline:
  build:
    image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    commands:
    - sbt universal:packageZipTarball
  docker_dev:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: razemio/metatron
    dockerfile: modules/fetchers/homematic/docker/dev/Dockerfile
    tags:
      - dev
  github_release:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    files:
    - target/scala-2.12/metatron-${DRONE_TAG}.jar
    checksum:
    - sha512
    when:
      event: tag
  docker_release:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: razemio/metatron
    dockerfile: modules/fetchers/homematic/docker/prod/Dockerfile
    auto_tag: true
    when:
      event: tag